name: Generate and Release CVs

on:
  push:
    paths:
      - 'cv/cv-config-pt.yml'
      - 'cv/cv-config-en.yml'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
  

permissions:
  contents: write  # Necessário para criar releases

jobs:
  generate-cv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install rendercv
      run: |
        python -m pip install --upgrade pip
        pip install rendercv[full]

    - name: Generate CV in Portuguese (Full)
      run: |
        rendercv render cv/cv-config-pt.yml --pdf-path joserdf-cv-pt.pdf

    - name: Generate CV in English (Full)
      run: |
        rendercv render cv/cv-config-en.yml --pdf-path joserdf-cv-en.pdf

    - name: Authenticate GitHub CLI
      run: |
        gh auth setup-git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      run: |
        tag=$(date +'%Y-%m-%d-%H-%M-%S')

        # Criar release com a data
        gh release create "$tag" joserdf-cv-pt.pdf joserdf-cv-en.pdf \
          --title "Curriculum - $tag" \
          --notes "Automatically generated releases of the curriculum in Portuguese and English."

        # Deletar release e tag "latest" (se existir)
        gh release delete latest --yes || true
        gh tag delete latest || true

        # Criar nova release "latest"
        gh release create "latest" joserdf-cv-pt.pdf joserdf-cv-en.pdf \
          --title "Curriculum - Latest" \
          --notes "Latest version of the automatically generated curriculum."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
